<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Pepper Cafe App" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="" src=".metadata" />
        <File name="index" src="html/index.html" />
        <File name="style" src="html/style.css" />
        <File name="app" src="html/app.js" />
        <File name="choice_sentences_light" src="behavior_1/Aldebaran/choice_sentences_light.xml" />
        <File name="heaven1" src="behavior_1/behavior_1/heaven1.ogg" />
        <File name="jquery.min" src="html/javascript/jquery.min.js" />
        <File name="qiClass" src="html/javascript/qiClass.js" />
        <File name="menu" src="html/javascript/data/menu.js" />
        <File name="pepper" src="html/javascript/data/pepper.js" />
        <File name="main-menu-page" src="html/javascript/jquery-components/main-menu-page.js" />
        <File name="qiClassTesting" src="html/javascript/qiClassTesting.js" />
        <File name="pages" src="html/javascript/utils/pages.js" />
        <File name="pepper" src="html/javascript/utils/pepper.js" />
        <File name="OpenSans-Bold" src="html/resources/fonts/OpenSans-Bold.woff2" />
        <File name="OpenSans-SemiBold" src="html/resources/fonts/OpenSans-SemiBold.woff2" />
        <File name="OpenSans" src="html/resources/fonts/OpenSans.woff2" />
        <File name="Raleway" src="html/resources/fonts/Raleway.woff2" />
        <File name="logo" src="html/resources/images/logo.png" />
        <File name="Pizza" src="html/resources/images/menu/Pizza.jpg" />
        <File name="americano" src="html/resources/images/menu/americano.jpg" />
        <File name="applepie" src="html/resources/images/menu/applepie.jpg" />
        <File name="apples" src="html/resources/images/menu/apples.jpg" />
        <File name="avocado" src="html/resources/images/menu/avocado.jpg" />
        <File name="bacon" src="html/resources/images/menu/bacon.jpg" />
        <File name="batter" src="html/resources/images/menu/batter.jpg" />
        <File name="bbqchickenpizza" src="html/resources/images/menu/bbqchickenpizza.jpg" />
        <File name="bbqsauce" src="html/resources/images/menu/bbqsauce.jpg" />
        <File name="beans" src="html/resources/images/menu/beans.jpg" />
        <File name="beef" src="html/resources/images/menu/beef.jpg" />
        <File name="bellpeppers" src="html/resources/images/menu/bellpeppers.jpg" />
        <File name="berries" src="html/resources/images/menu/berries.jpg" />
        <File name="bun" src="html/resources/images/menu/bun.jpg" />
        <File name="burittos" src="html/resources/images/menu/burittos.png" />
        <File name="burrito" src="html/resources/images/menu/burrito.jpg" />
        <File name="butter" src="html/resources/images/menu/butter.jpg" />
        <File name="cappuccino" src="html/resources/images/menu/cappuccino.jpg" />
        <File name="carrots" src="html/resources/images/menu/carrots.jpg" />
        <File name="celery" src="html/resources/images/menu/celery.jpg" />
        <File name="cheese" src="html/resources/images/menu/cheese.jpg" />
        <File name="chicken" src="html/resources/images/menu/chicken.jpg" />
        <File name="chocolatechips" src="html/resources/images/menu/chocolatechips.jpg" />
        <File name="cinnamon" src="html/resources/images/menu/cinnamon.jpg" />
        <File name="coffeebeans" src="html/resources/images/menu/coffeebeans.jpg" />
        <File name="cookie" src="html/resources/images/menu/cookie.jpg" />
        <File name="cookie" src="html/resources/images/menu/cookie.png" />
        <File name="cucumber" src="html/resources/images/menu/cucumber.jpg" />
        <File name="dough" src="html/resources/images/menu/dough.jpg" />
        <File name="dressing" src="html/resources/images/menu/dressing.jpg" />
        <File name="eggs" src="html/resources/images/menu/eggs.jpg" />
        <File name="espresso" src="html/resources/images/menu/espresso.jpg" />
        <File name="fish" src="html/resources/images/menu/fish.jpg" />
        <File name="fishandchips" src="html/resources/images/menu/fishandchips.jpg" />
        <File name="flour" src="html/resources/images/menu/flour.jpg" />
        <File name="foam" src="html/resources/images/menu/foam.jpg" />
        <File name="frenchfries" src="html/resources/images/menu/frenchfries.jpg" />
        <File name="freshfruit" src="html/resources/images/menu/freshfruit.jpg" />
        <File name="freshfruitsmoothie" src="html/resources/images/menu/freshfruitsmoothie.jpg" />
        <File name="fries" src="html/resources/images/menu/fries.png" />
        <File name="fruitcup" src="html/resources/images/menu/fruitcup.jpg" />
        <File name="fruits" src="html/resources/images/menu/fruits.jpg" />
        <File name="gardensalad" src="html/resources/images/menu/gardensalad.jpg" />
        <File name="garlic" src="html/resources/images/menu/garlic.jpg" />
        <File name="granola" src="html/resources/images/menu/granola.jpg" />
        <File name="grilledchicken" src="html/resources/images/menu/grilledchicken.jpg" />
        <File name="grilledsalmon" src="html/resources/images/menu/grilledsalmon.jpg" />
        <File name="honey" src="html/resources/images/menu/honey.jpg" />
        <File name="hummus" src="html/resources/images/menu/hummus.jpg" />
        <File name="hummussticks" src="html/resources/images/menu/hummussticks.jpg" />
        <File name="ice" src="html/resources/images/menu/ice.jpg" />
        <File name="icecream" src="html/resources/images/menu/icecream.jpg" />
        <File name="icedtea" src="html/resources/images/menu/icedtea.jpg" />
        <File name="largecoffee" src="html/resources/images/menu/largecoffee.jpg" />
        <File name="largeicedcoffee" src="html/resources/images/menu/largeicedcoffee.jpg" />
        <File name="largetea" src="html/resources/images/menu/largetea.jpg" />
        <File name="latte" src="html/resources/images/menu/latte.jpg" />
        <File name="lemon" src="html/resources/images/menu/lemon.jpg" />
        <File name="lemonade" src="html/resources/images/menu/lemonade.jpg" />
        <File name="lentils" src="html/resources/images/menu/lentils.jpg" />
        <File name="lettuce" src="html/resources/images/menu/lettuce.jpg" />
        <File name="mayo" src="html/resources/images/menu/mayo.jpg" />
        <File name="milk" src="html/resources/images/menu/milk.jpg" />
        <File name="mixedveg" src="html/resources/images/menu/mixedveg.jpg" />
        <File name="nori" src="html/resources/images/menu/nori.jpg" />
        <File name="oil" src="html/resources/images/menu/oil.jpg" />
        <File name="oliveoil" src="html/resources/images/menu/oliveoil.jpg" />
        <File name="onion" src="html/resources/images/menu/onion.jpg" />
        <File name="orangejuice" src="html/resources/images/menu/orangejuice.jpg" />
        <File name="oranges" src="html/resources/images/menu/oranges.jpg" />
        <File name="parfait" src="html/resources/images/menu/parfait.jpg" />
        <File name="parmesan" src="html/resources/images/menu/parmesan.jpg" />
        <File name="pasta" src="html/resources/images/menu/pasta.jpg" />
        <File name="potatoes" src="html/resources/images/menu/potatoes.jpg" />
        <File name="quinoa" src="html/resources/images/menu/quinoa.jpg" />
        <File name="quinoasalad" src="html/resources/images/menu/quinoasalad.jpg" />
        <File name="rice" src="html/resources/images/menu/rice.jpg" />
        <File name="salad" src="html/resources/images/menu/salad.jpg" />
        <File name="salmon" src="html/resources/images/menu/salmon.jpg" />
        <File name="salsa" src="html/resources/images/menu/salsa.jpg" />
        <File name="sandwich" src="html/resources/images/menu/sandwich.jpg" />
        <File name="sauce" src="html/resources/images/menu/sauce.jpg" />
        <File name="sesameoil" src="html/resources/images/menu/sesameoil.jpg" />
        <File name="sidesalad" src="html/resources/images/menu/sidesalad.jpg" />
        <File name="smallcoffee" src="html/resources/images/menu/smallcoffee.jpg" />
        <File name="smallicedcoffee" src="html/resources/images/menu/smallicedcoffee.jpg" />
        <File name="smalltea" src="html/resources/images/menu/smalltea.jpg" />
        <File name="soda" src="html/resources/images/menu/soda.jpg" />
        <File name="sourcream" src="html/resources/images/menu/sourcream.jpg" />
        <File name="soysauce" src="html/resources/images/menu/soysauce.jpg" />
        <File name="spaghetti" src="html/resources/images/menu/spaghetti.jpg" />
        <File name="spices" src="html/resources/images/menu/spices.jpg" />
        <File name="stirfry" src="html/resources/images/menu/stirfry.jpg" />
        <File name="sugar" src="html/resources/images/menu/sugar.jpg" />
        <File name="sushi" src="html/resources/images/menu/sushi.jpg" />
        <File name="sweetpotatoes" src="html/resources/images/menu/sweetpotatoes.jpg" />
        <File name="sweetpotatofries" src="html/resources/images/menu/sweetpotatofries.jpg" />
        <File name="tacosalad" src="html/resources/images/menu/tacosalad.jpg" />
        <File name="tartarsauce" src="html/resources/images/menu/tartarsauce.jpg" />
        <File name="tea" src="html/resources/images/menu/tea.jpg" />
        <File name="tealeaves" src="html/resources/images/menu/tealeaves.jpg" />
        <File name="toast" src="html/resources/images/menu/toast.jpg" />
        <File name="tomatoes" src="html/resources/images/menu/tomatoes.jpg" />
        <File name="tortilla" src="html/resources/images/menu/tortilla.jpg" />
        <File name="turkey" src="html/resources/images/menu/turkey.jpg" />
        <File name="vanilla" src="html/resources/images/menu/vanilla.jpg" />
        <File name="veganlentilsoup" src="html/resources/images/menu/veganlentilsoup.jpg" />
        <File name="vegetables" src="html/resources/images/menu/vegetables.jpg" />
        <File name="veggieburger" src="html/resources/images/menu/veggieburger.jpg" />
        <File name="veggiepatty" src="html/resources/images/menu/veggiepatty.jpg" />
        <File name="vegstock" src="html/resources/images/menu/vegstock.jpg" />
        <File name="water" src="html/resources/images/menu/water.jpg" />
        <File name="yogurt" src="html/resources/images/menu/yogurt.jpg" />
        <File name="yogurtgranola" src="html/resources/images/menu/yogurtgranola.jpg" />
        <File name="arrow-in-circle" src="html/resources/images/other/arrow-in-circle.svg" />
        <File name="chaser-dog-paw" src="html/resources/images/scc/chaser-dog-paw.png" />
        <File name="scc-logo" src="html/resources/images/scc/scc-logo.png" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
    </Translations>
</Package>
